---
title: fluore_scente
timezone: UTC
collections:
  drawings:
    title: Drawings
    output: true
  placeholder-posts:
    title: Placeholder Posts
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  services:
    title: Services
    output: true
  styles-and-components:
    title: Styles And Components
    output: true
  team_members:
    title: Team Members
    output: true
  typography-bold-paragraph-styles:
    title: Typography Bold Paragraph Styles
    output: true
  typography-heading-styles:
    title: Typography Heading Styles
    output: true
  typography-paragraph-styles:
    title: Typography Paragraph Styles
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: ''
  values:
    layout: post
    logo: assets/images/fluore_scente-logo.png
    image: true
tagline: Identidad visual, ilustraciones y sitios, web para organizaciones conscientes
  y amigables.
email: hola@fluore&shy;scente.design
description: Identidad visual, ilustraciones y sitios, web para organizaciones conscientes
  y amigables. Ubicado en Medellín, Colombia.
author: fluore_scente
image: assets/images/fluorescente-card-image.png
logo: assets/images/fluore_scente-logo.png
url: https://fluorescente.design
github_username: fluorescente
ko-fi_url: https://ko-fi.com/fluorescente
lang: es
locale: es_CO
link_to_projects: Ver proyectos
link_to_contact: Escríbenos
link_to_more_projects: Más proyectos
github_url: https://github.com/fluorescente
behance_url: https://www.behance.net/fluore_scente
dribbble_url: https://dribbble.com/fluore_scente
telegram_url: https://t.me/joinchat/J9QQERoNyllnuRbAYo7iwg
link_to_behance: Más proyectos en Behance
link_to_dribbble: Más dibujos en Dribbble
suscribe_call_to_action: Suscríbete al blog :)
suscribe_button: Suscríbete
theme: minima
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
