- platform: "weibo"
  url: "#"
  aria-label: "Weibo"
  target: "_blank"
- platform: "xiao-hong-shu"
  url: "#"
  aria-label: "Xiao Hong Shu"
  target: "_blank"
- platform: "wechat"
  url: "#"
  aria-label: "Wechat"
  target: "_blank"  
